service: aws-service

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev
  environment:
    CLIENT_ID: !GetAtt CognitoUserPoolClient.ClientId 
    USERS_TABLE: !Ref UsersTable
  iamRoleStatements:
    - Effect: "Allow"
      Action: 
        - dynamodb:PutItem
        - dynamodb:GetItem
      Resource: !GetAtt UsersTable.Arn


functions:
  signUp: 
    handler: handler.signUp
    events: 
      - http:
          path: signUp
          method: post
          cors: true
  confirmSignUp:
    handler: handler.confirmSignUp
    events:
      - http:
          path: confirmSignUp
          method: post
          cors: true
  login:
    handler: handler.login
    events:
      - http:
          path: login
          method: post
          cors: true

resources:
  Resources:
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: my-pool
        AutoVerifiedAttributes: 
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 6
            RequireUppercase: true
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: false
    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: my-pool-client
        UserPoolId: !Ref CognitoUserPool
        GenerateSecret: false
        ExplicitAuthFlows:
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
          - ALLOW_USER_SRP_AUTH

    UsersTable: 
      Type: AWS::DynamoDB::Table  
      Properties:
        TableName: UsersTable
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST


  Outputs:  
    UserPoolId:
      Description: Cognito User Pool ID
      Value: !Ref CognitoUserPool
    UserPoolClientId:
      Description: Cognito App Client ID
      Value: !Ref CognitoUserPoolClient
    UsersTableName:
      Description: Users DynamoDB Table Name
      Value: !Ref UsersTable